# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15LHbHwprKN_aDbxEU0ZtQEbqCfiH2xTw
"""

import pandas as pd
import numpy as np

import re

# split is used to divide data into training and testing parts
from sklearn.model_selection import train_test_split

# LabelEncoder converts text labels into numbers

from sklearn.preprocessing import LabelEncoder

# CountVectorizer converts text into numerical features
from sklearn.feature_extraction.text import CountVectorizer

# MultinomialNB is a simple and popular model for text classification
from sklearn.naive_bayes import MultinomialNB

# These are  to evaluate the model
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# We are creating the dataset manually so it can run directly in Colab
# label = spam or ham
# message = the text message

data = {
    "label": [
        "ham", "spam", "ham", "spam", "ham", "spam", "ham", "spam", "ham", "spam",
        "ham", "spam", "ham", "spam", "ham", "spam", "ham", "spam", "ham", "spam"
    ],
    "message": [
        "Hey, are we meeting today?",
        "Congratulations! You won a free iPhone. Click now!",
        "Please send me the notes of today class",
        "Win cash prize now by clicking this link",
        "Can you call me after lunch?",
        "Limited offer! Buy now and get 50 percent discount",
        "I am on the way to college",
        "You have been selected for a free vacation",
        "Let's study together in the evening",
        "Claim your lottery reward today",
        "Can you help me with Python homework?",
        "Urgent! Your account has won a huge reward",
        "Where are you now?",
        "Free entry in contest, click here now",
        "I will reach home by 8 PM",
        "Get a free gift voucher instantly",
        "Did you complete the assignment?",
        "Exclusive deal only for you, act fast",
        "Let's go for tea after class",
        "You are a lucky winner, claim your prize"
    ]
}

# Convert dictionary into DataFrame
df = pd.DataFrame(data)

# Show first 5 rows
print("First 5 rows of dataset:")
print(df.head())

# Shape shows number of rows and columns
print("\nDataset shape:")
print(df.shape)

# Column names
print("\nColumn names:")
print(df.columns)

# Basic info
print("\nDataset info:")
df.info()

# Check missing values
print("\nMissing values:")
print(df.isnull().sum())

# This function will clean the text messages
# It does the following:
# 1. converts text to lowercase
# 2. removes numbers
# 3. removes punctuation/special characters
# 4. removes extra spaces

def clean_text(text):
    # convert to lowercase
    text = text.lower()

    # remove numbers
    text = re.sub(r'\d+', '', text)

    # remove special characters and punctuation
    text = re.sub(r'[^a-zA-Z\s]', '', text)

    # remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

# Apply cleaning function to message column
df["clean_message"] = df["message"].apply(clean_text)

print("\nDataset after text cleaning:")
print(df[["message", "clean_message"]].head())

# Machine learning model cannot understand text labels directly
# So we convert:
# ham  -> 0
# spam -> 1

label_encoder = LabelEncoder()
df["label_encoded"] = label_encoder.fit_transform(df["label"])

print("\nOriginal and encoded labels:")

print(df[["label", "label_encoded"]].head())

print("\nLabel mapping:")
for i, class_name in enumerate(label_encoder.classes_):
  print(f"{class_name} --> {i}")

# X = input feature (cleaned message text)
# y = target output (encoded label)

X = df["clean_message"]
y = df["label_encoded"]

print("\nFeature sample:")
print(X.head())

print("\nTarget sample:")
print(y.head())

# We split the data into:
# 80% training data
# 20% testing data

X_train, X_test, y_train, y_test = train_test_split(
    X,y, test_size=0.2, random_state=42
)

print("\nTrain-Test Split Shapes:")
print("X_train:", X_train.shape)
print("X-test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

# Machine learning models need numeric input
# CountVectorizer converts text into a bag-of-words numerical format

vectorizer = CountVectorizer()

X_train_vectorized = vectorizer.fit_transform(X_train)

X_test_vectorized = vectorizer.transform(X_test)

print("\nShape after vectorization:")
print("X_train_vectorized:", X_train_vectorized.shape)
print("X_test_vectorized:", X_test_vectorized.shape)

print("\nSample vocabulary words:")
print(list(vectorizer.vocabulary_.keys())[:10])

# Multinomial Naive Bayes works very well for text classification

model = MultinomialNB()

# train the model using training data
model.fit(X_train_vectorized, y_train)

print("\nModel trained successfully!")

# Predict on test data
y_pred = model.predict(X_test_vectorized)

print("\nPredicted values:")
print(y_pred)

print("\nActual values:")
print(y_test.values)

# Accuracy tells how many predictions are correct
accuracy = accuracy_score(y_test, y_pred)

print("\nAccuracy of model:")
print(accuracy)

# classification report gives precision, recall, f1-score
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Confusion matrix shows correct and incorrect predictions
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Here we test our model on new messages written by us

new_messages =[
    "Congratulations you have won a free gift",
    "Can you send me the class link",
    "Claim your cash prize now",
    "I am coming in 10 minutes",
    "Exclusive offer only today buy now"
]

# clean the new messages
cleaned_new_messages = [clean_text(msg) for msg in new_messages]

#Convert them into numerical format
new_messages_vectorized = vectorizer.transform(cleaned_new_messages)

#predict spam or ham
new_predictions = model.predict(new_messages_vectorized)

print("\nNew Message Predictions:")
for msg, pred in zip(new_messages, new_predictions):
  label_name = label_encoder.inverse_transform([pred])[0]
  print(f"Message: {msg}")
  print(f"Prediction: {label_name}\n")
  print("-" * 50)